// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: moderation

use serde::{Deserialize, Serialize};

/// A list of the categories, and whether they are flagged or not.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Categories {
    /// Content that expresses, incites, or promotes harassing language towards any
    pub harassment: bool,
    /// Harassment content that also includes violence or serious harm towards any
    #[serde(rename = "harassment/threatening")]
    pub harassment_threatening: bool,
    /// Content that expresses, incites, or promotes hate based on race, gender,
    pub hate: bool,
    /// Hateful content that also includes violence or serious harm towards the targeted
    #[serde(rename = "hate/threatening")]
    pub hate_threatening: bool,
    /// Content that includes instructions or advice that facilitate the planning or
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub illicit: Option<bool>,
    /// Content that includes instructions or advice that facilitate the planning or
    #[serde(rename = "illicit/violent")]
    pub illicit_violent: Option<bool>,
    /// Content that promotes, encourages, or depicts acts of self-harm, such as
    #[serde(rename = "self-harm")]
    pub self_harm: bool,
    /// Content that encourages performing acts of self-harm, such as suicide, cutting,
    #[serde(rename = "self-harm/instructions")]
    pub self_harm_instructions: bool,
    /// Content where the speaker expresses that they are engaging or intend to engage
    #[serde(rename = "self-harm/intent")]
    pub self_harm_intent: bool,
    /// Content meant to arouse sexual excitement, such as the description of sexual
    pub sexual: bool,
    /// Sexual content that includes an individual who is under 18 years old.
    #[serde(rename = "sexual/minors")]
    pub sexual_minors: bool,
    /// Content that depicts death, violence, or physical injury.
    pub violence: bool,
    /// Content that depicts death, violence, or physical injury in graphic detail.
    #[serde(rename = "violence/graphic")]
    pub violence_graphic: bool,
}

/// A list of the categories along with the input type(s) that the score applies to.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct CategoryAppliedInputTypes {
    /// The applied input type(s) for the category 'harassment'.
    pub harassment: Vec<String>,
    /// The applied input type(s) for the category 'harassment/threatening'.
    #[serde(rename = "harassment/threatening")]
    pub harassment_threatening: Vec<String>,
    /// The applied input type(s) for the category 'hate'.
    pub hate: Vec<String>,
    /// The applied input type(s) for the category 'hate/threatening'.
    #[serde(rename = "hate/threatening")]
    pub hate_threatening: Vec<String>,
    /// The applied input type(s) for the category 'illicit'.
    pub illicit: Vec<String>,
    /// The applied input type(s) for the category 'illicit/violent'.
    #[serde(rename = "illicit/violent")]
    pub illicit_violent: Vec<String>,
    /// The applied input type(s) for the category 'self-harm'.
    #[serde(rename = "self-harm")]
    pub self_harm: Vec<serde_json::Value>,
    /// The applied input type(s) for the category 'self-harm/instructions'.
    #[serde(rename = "self-harm/instructions")]
    pub self_harm_instructions: Vec<serde_json::Value>,
    /// The applied input type(s) for the category 'self-harm/intent'.
    #[serde(rename = "self-harm/intent")]
    pub self_harm_intent: Vec<serde_json::Value>,
    /// The applied input type(s) for the category 'sexual'.
    pub sexual: Vec<serde_json::Value>,
    /// The applied input type(s) for the category 'sexual/minors'.
    #[serde(rename = "sexual/minors")]
    pub sexual_minors: Vec<String>,
    /// The applied input type(s) for the category 'violence'.
    pub violence: Vec<serde_json::Value>,
    /// The applied input type(s) for the category 'violence/graphic'.
    #[serde(rename = "violence/graphic")]
    pub violence_graphic: Vec<serde_json::Value>,
}

/// A list of the categories along with their scores as predicted by model.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct CategoryScores {
    /// The score for the category 'harassment'.
    pub harassment: f64,
    /// The score for the category 'harassment/threatening'.
    #[serde(rename = "harassment/threatening")]
    pub harassment_threatening: f64,
    /// The score for the category 'hate'.
    pub hate: f64,
    /// The score for the category 'hate/threatening'.
    #[serde(rename = "hate/threatening")]
    pub hate_threatening: f64,
    /// The score for the category 'illicit'.
    pub illicit: f64,
    /// The score for the category 'illicit/violent'.
    #[serde(rename = "illicit/violent")]
    pub illicit_violent: f64,
    /// The score for the category 'self-harm'.
    #[serde(rename = "self-harm")]
    pub self_harm: f64,
    /// The score for the category 'self-harm/instructions'.
    #[serde(rename = "self-harm/instructions")]
    pub self_harm_instructions: f64,
    /// The score for the category 'self-harm/intent'.
    #[serde(rename = "self-harm/intent")]
    pub self_harm_intent: f64,
    /// The score for the category 'sexual'.
    pub sexual: f64,
    /// The score for the category 'sexual/minors'.
    #[serde(rename = "sexual/minors")]
    pub sexual_minors: f64,
    /// The score for the category 'violence'.
    pub violence: f64,
    /// The score for the category 'violence/graphic'.
    #[serde(rename = "violence/graphic")]
    pub violence_graphic: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Moderation {
    /// A list of the categories, and whether they are flagged or not.
    pub categories: serde_json::Value,
    /// A list of the categories along with the input type(s) that the score applies to.
    pub category_applied_input_types: serde_json::Value,
    /// A list of the categories along with their scores as predicted by model.
    pub category_scores: serde_json::Value,
    /// Whether any of the below categories are flagged.
    pub flagged: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ModerationCreateParams {
    /// Input (or inputs) to classify.
    pub input: serde_json::Value,
    /// The content moderation model you would like to use.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
}

/// Represents if a given text input is potentially harmful.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ModerationCreateResponse {
    /// The unique identifier for the moderation request.
    pub id: String,
    /// The model used to generate the moderation results.
    pub model: String,
    /// A list of moderation objects.
    pub results: Vec<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ModerationModel {
    #[serde(rename = "omni-moderation-latest")]
    OmniModerationLatest,
    #[serde(rename = "omni-moderation-2024-09-26")]
    OmniModeration20240926,
    #[serde(rename = "text-moderation-latest")]
    TextModerationLatest,
    #[serde(rename = "text-moderation-stable")]
    TextModerationStable,
}
