// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: file

use serde::{Deserialize, Serialize};

pub type FileChunkingStrategy = serde_json::Value;

pub type FileContent = String;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileCreateParams {
    /// The File object (not file name) to be uploaded.
    pub file: serde_json::Value,
    /// The intended purpose of the uploaded file. One of:
    pub purpose: FilePurpose,
    /// The expiration policy for a file.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_after: Option<ExpiresAfter>,
}

/// The expiration policy for a file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ExpiresAfter {
    /// Anchor timestamp after which the expiration policy applies.
    pub anchor: String,
    /// The number of seconds after the anchor time that the file will expire.
    pub seconds: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileDeleted {
    pub id: String,
    pub deleted: bool,
    pub object: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileListParamsOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileListParams {
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// A limit on the number of objects to be returned.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub order: Option<FileListParamsOrder>,
    /// Only return files with the given purpose.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub purpose: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileObjectPurpose {
    #[serde(rename = "assistants")]
    Assistants,
    #[serde(rename = "assistants_output")]
    AssistantsOutput,
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "batch_output")]
    BatchOutput,
    #[serde(rename = "fine-tune")]
    FineTune,
    #[serde(rename = "fine-tune-results")]
    FineTuneResults,
    #[serde(rename = "vision")]
    Vision,
    #[serde(rename = "user_data")]
    UserData,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileObjectStatus {
    #[serde(rename = "uploaded")]
    Uploaded,
    #[serde(rename = "processed")]
    Processed,
    #[serde(rename = "error")]
    Error,
}

/// The `File` object represents a document that has been uploaded to OpenAI.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileObject {
    /// The file identifier, which can be referenced in the API endpoints.
    pub id: String,
    /// The size of the file, in bytes.
    pub bytes: i64,
    /// The Unix timestamp (in seconds) for when the file was created.
    pub created_at: i64,
    /// The name of the file.
    pub filename: String,
    /// The object type, which is always `file`.
    pub object: String,
    /// The intended purpose of the file.
    pub purpose: FileObjectPurpose,
    /// Deprecated.
    pub status: FileObjectStatus,
    /// The Unix timestamp (in seconds) for when the file will expire.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_at: Option<i64>,
    /// Deprecated.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub status_details: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FilePurpose {
    #[serde(rename = "assistants")]
    Assistants,
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "fine-tune")]
    FineTune,
    #[serde(rename = "vision")]
    Vision,
    #[serde(rename = "user_data")]
    UserData,
    #[serde(rename = "evals")]
    Evals,
}

/// This is returned when the chunking strategy is unknown.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct OtherFileChunkingStrategyObject {
    /// Always `other`.
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct StaticFileChunkingStrategy {
    /// The number of tokens that overlap between chunks. The default value is `400`.
    pub chunk_overlap_tokens: i64,
    /// The maximum number of tokens in each chunk.
    pub max_chunk_size_tokens: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct StaticFileChunkingStrategyObject {
    #[serde(rename = "static")]
    pub static_: StaticFileChunkingStrategy,
    /// Always `static`.
    #[serde(rename = "type")]
    pub type_: String,
}
