// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: vector_stores

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileBatchCreateParams {
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<serde_json::Value>,
    /// A list of [File](https://platform.openai.com/docs/api-reference/files) IDs that
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<serde_json::Value>,
    /// A list of objects that each include a `file_id` plus optional `attributes` or
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub files: Option<Vec<File>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct File {
    /// A [File](https://platform.openai.com/docs/api-reference/files) ID that the
    pub file_id: String,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileBatchListFilesParamsFilter {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileBatchListFilesParamsOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileBatchListFilesParams {
    pub vector_store_id: String,
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub before: Option<String>,
    /// Filter by file status.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<FileBatchListFilesParamsFilter>,
    /// A limit on the number of objects to be returned.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub order: Option<FileBatchListFilesParamsOrder>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileContentResponse {
    /// The text content
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub text: Option<String>,
    /// The content type (currently only `"text"`)
    #[serde(rename = "type", skip_serializing_if = "Option::is_none", default)]
    pub type_: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileCreateParams {
    /// A [File](https://platform.openai.com/docs/api-reference/files) ID that the
    pub file_id: String,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileListParamsFilter {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum FileListParamsOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileListParams {
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub before: Option<String>,
    /// Filter by file status.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filter: Option<FileListParamsFilter>,
    /// A limit on the number of objects to be returned.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub order: Option<FileListParamsOrder>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileUpdateParams {
    pub vector_store_id: String,
    /// Set of 16 key-value pairs that can be attached to an object.
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum LastErrorCode {
    #[serde(rename = "server_error")]
    ServerError,
    #[serde(rename = "unsupported_file")]
    UnsupportedFile,
    #[serde(rename = "invalid_file")]
    InvalidFile,
}

/// The last error associated with this vector store file.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct LastError {
    /// One of `server_error`, `unsupported_file`, or `invalid_file`.
    pub code: LastErrorCode,
    /// A human-readable description of the error.
    pub message: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum VectorStoreFileStatus {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

/// A list of files attached to a vector store.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreFile {
    /// The identifier, which can be referenced in API endpoints.
    pub id: String,
    /// The Unix timestamp (in seconds) for when the vector store file was created.
    pub created_at: i64,
    /// The last error associated with this vector store file.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_error: Option<LastError>,
    /// The object type, which is always `vector_store.file`.
    pub object: String,
    /// The status of the vector store file, which can be either `in_progress`,
    pub status: VectorStoreFileStatus,
    /// The total vector store usage in bytes.
    pub usage_bytes: i64,
    /// The ID of the
    pub vector_store_id: String,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// The strategy used to chunk the file.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct FileCounts {
    /// The number of files that where cancelled.
    pub cancelled: i64,
    /// The number of files that have been processed.
    pub completed: i64,
    /// The number of files that have failed to process.
    pub failed: i64,
    /// The number of files that are currently being processed.
    pub in_progress: i64,
    /// The total number of files.
    pub total: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum VectorStoreFileBatchStatus {
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "failed")]
    Failed,
}

/// A batch of files attached to a vector store.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreFileBatch {
    /// The identifier, which can be referenced in API endpoints.
    pub id: String,
    /// The Unix timestamp (in seconds) for when the vector store files batch was
    pub created_at: i64,
    pub file_counts: FileCounts,
    /// The object type, which is always `vector_store.file_batch`.
    pub object: String,
    /// The status of the vector store files batch, which can be either `in_progress`,
    pub status: VectorStoreFileBatchStatus,
    /// The ID of the
    pub vector_store_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreFileDeleted {
    pub id: String,
    pub deleted: bool,
    pub object: String,
}

/// The expiration policy for a vector store.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ExpiresAfter {
    /// Anchor timestamp after which the expiration policy applies.
    pub anchor: String,
    /// The number of days after the anchor time that the vector store will expire.
    pub days: i64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum VectorStoreStatus {
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "completed")]
    Completed,
}

/// A vector store is a collection of processed files can be used by the `file_search` tool.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStore {
    /// The identifier, which can be referenced in API endpoints.
    pub id: String,
    /// The Unix timestamp (in seconds) for when the vector store was created.
    pub created_at: i64,
    pub file_counts: FileCounts,
    /// The Unix timestamp (in seconds) for when the vector store was last active.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub last_active_at: Option<i64>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The name of the vector store.
    pub name: String,
    /// The object type, which is always `vector_store`.
    pub object: String,
    /// The status of the vector store, which can be either `expired`, `in_progress`, or
    pub status: VectorStoreStatus,
    /// The total number of bytes used by the files in the vector store.
    pub usage_bytes: i64,
    /// The expiration policy for a vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_after: Option<ExpiresAfter>,
    /// The Unix timestamp (in seconds) for when the vector store will expire.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_at: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreCreateParams {
    /// The chunking strategy used to chunk the file(s).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub chunking_strategy: Option<serde_json::Value>,
    /// A description for the vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub description: Option<String>,
    /// The expiration policy for a vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_after: Option<ExpiresAfter>,
    /// A list of [File](https://platform.openai.com/docs/api-reference/files) IDs that
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub file_ids: Option<serde_json::Value>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The name of the vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreDeleted {
    pub id: String,
    pub deleted: bool,
    pub object: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum VectorStoreListParamsOrder {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreListParams {
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub before: Option<String>,
    /// A limit on the number of objects to be returned.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
    /// Sort order by the `created_at` timestamp of the objects.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub order: Option<VectorStoreListParamsOrder>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreSearchParams {
    /// A query string for a search
    pub query: String,
    /// A filter to apply based on file attributes.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub filters: Option<Filters>,
    /// The maximum number of results to return.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub max_num_results: Option<i64>,
    /// Ranking options for search.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub ranking_options: Option<RankingOptions>,
    /// Whether to rewrite the natural language query for vector search.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub rewrite_query: Option<bool>,
}

pub type Filters = serde_json::Value;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum RankingOptionsRanker {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "auto")]
    Auto,
    #[serde(rename = "default-2024-11-15")]
    Default20241115,
}

/// Ranking options for search.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct RankingOptions {
    /// Enable re-ranking; set to `none` to disable, which can help reduce latency.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub ranker: Option<RankingOptionsRanker>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub score_threshold: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreContent {
    /// The text content returned from search.
    pub text: String,
    /// The type of content.
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreSearchResponse {
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub attributes: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Content chunks from the file.
    pub content: Vec<VectorStoreContent>,
    /// The ID of the vector store file.
    pub file_id: String,
    /// The name of the vector store file.
    pub filename: String,
    /// The similarity score for the result.
    pub score: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct VectorStoreUpdateParams {
    /// The expiration policy for a vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_after: Option<ExpiresAfter>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The name of the vector store.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub name: Option<String>,
}
