// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: content_provenance
#![allow(unused_imports)]

use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ResultC2PAOutcome {
    #[serde(rename = "detected")]
    Detected,
    #[serde(rename = "not_detected")]
    NotDetected,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ResultC2PAValidationState {
    #[serde(rename = "trusted")]
    Trusted,
    #[serde(rename = "valid")]
    Valid,
    #[serde(rename = "invalid")]
    Invalid,
    #[serde(rename = "not_present")]
    NotPresent,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ResultC2PA {
    /// The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub generated_at: Option<String>,
    /// The C2PA manifest issuer, when available.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub issuer: Option<String>,
    /// The OpenAI model recorded by the provenance signal, when available.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// Whether a supported OpenAI C2PA provenance signal was detected. If
    pub outcome: ResultC2PAOutcome,
    /// The provenance signal type. Always `c2pa`.
    #[serde(rename = "type")]
    pub type_: String,
    /// The validation status of the C2PA manifest in the uploaded image.
    pub validation_state: ResultC2PAValidationState,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum ResultSynthIDOutcome {
    #[serde(rename = "detected")]
    Detected,
    #[serde(rename = "not_detected")]
    NotDetected,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ResultSynthID {
    /// The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub generated_at: Option<String>,
    /// The OpenAI model recorded by the provenance signal, when available.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
    pub outcome: ResultSynthIDOutcome,
    /// The provenance signal type. Always `synthid`.
    #[serde(rename = "type")]
    pub type_: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct ContentProvenanceCheckCreateParams {
    /// The image or audio file to check for supported OpenAI provenance signals.
    pub file: serde_json::Value,
}
