/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Client {
  constructor(options?: ClientOptions | undefined | null)
  createChatCompletion(request: Record<string, any>): Promise<Record<string, any>>
  /**
   * Chat completion with structured output — auto-sets response_format to json_schema.
   *
   * Pass a JSON schema object. Returns the parsed content as a JS object.
   * Works with `zod-to-json-schema` or any JSON Schema generator.
   */
  createChatParsed(request: Record<string, any>, schemaName: string, schema: Record<string, any>): Promise<{ completion: Record<string, any>, parsed: any }>
  /** Responses API with structured output — auto-sets text.format to json_schema. */
  createResponseParsed(request: Record<string, any>, schemaName: string, schema: Record<string, any>): Promise<{ response: Record<string, any>, parsed: any }>
  createChatStream(request: Record<string, any>, tsfn: (err: Error | null, event: Record<string, any> | null) => void): Promise<void>
  createResponse(request: Record<string, any>): Promise<Record<string, any>>
  /**
   * Fast path: accepts pre-serialized JSON string, avoids napi object→Value copy.
   * JS does JSON.stringify once, Rust sends bytes directly — single pass.
   */
  createResponseFast(jsonBody: string): Promise<Record<string, any>>
  /** Fast path for streaming: accepts pre-serialized JSON string. */
  createStreamFast(jsonBody: string, tsfn: (err: Error | null, event: Record<string, any> | null) => void): Promise<void>
  createText(model: string, input: string, maxOutputTokens?: number): Promise<string>
  createStoredResponseId(model: string, input: string, maxOutputTokens?: number): Promise<string>
  createTextFollowup(model: string, input: string, previousResponseId: string, maxOutputTokens?: number): Promise<string>
  createStream(request: Record<string, any>, tsfn: (err: Error | null, event: Record<string, any> | null) => void): Promise<void>
  wsSession(): Promise<NodeWsSession>
}

export declare class NodeWsSession {
  send(model: string, input: string): Promise<Record<string, any>>
  close(): Promise<void>
}

export interface ClientOptions {
  baseUrl?: string
  apiKey?: string
}
