// AUTO-GENERATED by py2rust — do not edit.
// Re-generate: python3 scripts/py2rust.py sync <python_dir> <rust_dir>
// Domain: batch

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchErrors {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub data: Option<Vec<serde_json::Value>>,
    /// The object type, which is always `list`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub object: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum BatchStatus {
    #[serde(rename = "validating")]
    Validating,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "finalizing")]
    Finalizing,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "expired")]
    Expired,
    #[serde(rename = "cancelling")]
    Cancelling,
    #[serde(rename = "cancelled")]
    Cancelled,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct Batch {
    pub id: String,
    /// The time frame within which the batch should be processed.
    pub completion_window: String,
    /// The Unix timestamp (in seconds) for when the batch was created.
    pub created_at: i64,
    /// The OpenAI API endpoint used by the batch.
    pub endpoint: String,
    /// The ID of the input file for the batch.
    pub input_file_id: String,
    /// The object type, which is always `batch`.
    pub object: String,
    /// The current status of the batch.
    pub status: BatchStatus,
    /// The Unix timestamp (in seconds) for when the batch was cancelled.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub cancelled_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch started cancelling.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub cancelling_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch was completed.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub completed_at: Option<i64>,
    /// The ID of the file containing the outputs of requests with errors.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error_file_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub errors: Option<serde_json::Value>,
    /// The Unix timestamp (in seconds) for when the batch expired.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expired_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch will expire.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub expires_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch failed.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub failed_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch started finalizing.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub finalizing_at: Option<i64>,
    /// The Unix timestamp (in seconds) for when the batch started processing.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub in_progress_at: Option<i64>,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// Model ID used to process the batch, like `gpt-5-2025-08-07`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub model: Option<String>,
    /// The ID of the file containing the outputs of successfully executed requests.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub output_file_id: Option<String>,
    /// The request counts for different statuses within the batch.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub request_counts: Option<serde_json::Value>,
    /// Represents token usage details including input tokens, output tokens, a
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub usage: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
#[non_exhaustive]
pub enum BatchCreateParamsEndpoint {
    #[serde(rename = "/v1/responses")]
    V1Responses,
    #[serde(rename = "/v1/chat/completions")]
    V1ChatCompletions,
    #[serde(rename = "/v1/embeddings")]
    V1Embeddings,
    #[serde(rename = "/v1/completions")]
    V1Completions,
    #[serde(rename = "/v1/moderations")]
    V1Moderations,
    #[serde(rename = "/v1/images/generations")]
    V1ImagesGenerations,
    #[serde(rename = "/v1/images/edits")]
    V1ImagesEdits,
    #[serde(rename = "/v1/videos")]
    V1Videos,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchCreateParams {
    /// The time frame within which the batch should be processed.
    pub completion_window: String,
    /// The endpoint to be used for all requests in the batch.
    pub endpoint: BatchCreateParamsEndpoint,
    /// The ID of an uploaded file that contains requests for the new batch.
    pub input_file_id: String,
    /// Set of 16 key-value pairs that can be attached to an object.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub metadata: Option<serde_json::Value>,
    /// The expiration policy for the output and/or error file that are generated for a
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub output_expires_after: Option<serde_json::Value>,
}

/// The expiration policy for the output and/or error file that are generated for a batch.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct OutputExpiresAfter {
    /// Anchor timestamp after which the expiration policy applies.
    pub anchor: String,
    /// The number of seconds after the anchor time that the file will expire.
    pub seconds: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchError {
    /// An error code identifying the error type.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub code: Option<String>,
    /// The line number of the input file where the error occurred, if applicable.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub line: Option<i64>,
    /// A human-readable message providing more details about the error.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub message: Option<String>,
    /// The name of the parameter that caused the error, if applicable.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub param: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchListParams {
    /// A cursor for use in pagination.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub after: Option<String>,
    /// A limit on the number of objects to be returned.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub limit: Option<i64>,
}

/// The request counts for different statuses within the batch.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchRequestCounts {
    /// Number of requests that have been completed successfully.
    pub completed: i64,
    /// Number of requests that have failed.
    pub failed: i64,
    /// Total number of requests in the batch.
    pub total: i64,
}

/// A detailed breakdown of the input tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct InputTokensDetails {
    /// The number of tokens that were retrieved from the cache.
    pub cached_tokens: i64,
}

/// A detailed breakdown of the output tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct OutputTokensDetails {
    /// The number of reasoning tokens.
    pub reasoning_tokens: i64,
}

/// Represents token usage details including input tokens, output tokens, a
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "structured", derive(schemars::JsonSchema))]
pub struct BatchUsage {
    /// The number of input tokens.
    pub input_tokens: i64,
    /// A detailed breakdown of the input tokens.
    pub input_tokens_details: serde_json::Value,
    /// The number of output tokens.
    pub output_tokens: i64,
    /// A detailed breakdown of the output tokens.
    pub output_tokens_details: serde_json::Value,
    /// The total number of tokens used.
    pub total_tokens: i64,
}
